import { Source } from "../types";

export const sources: Source[] = [
  {
    id: "1",
    schedule: "everyday",
    timeSpan: "1",
    title: "Hacker News",
    url: "https://news.ycombinator.com/",
    rssLink: "https://news.ycombinator.com/rss",
    favicon: "https://news.ycombinator.com/y18.svg",
    tags: ["Technology"],
    customDays: [],
  },
  {
    id: "2",
    schedule: "everyday",
    timeSpan: "1",
    title: "PH Deck",
    url: "https://www.phdeck.com/",
    rssLink: "https://www.producthunt.com/feed",
    favicon: "https://www.phdeck.com/favicon.ico",
    tags: ["Product"],
    customDays: [],
  },
  {
    id: "3",
    schedule: "everyday",
    timeSpan: "1",
    title: "AInvest",
    url: "https://www.ainvest.com/",
    rssLink: "https://rsshub.app/ainvest/article",
    favicon: "https://www.ainvest.com/wencai-ssr/_nuxt/icons/icon_64x64.d7847c.png",
    tags: ["AI", "Finance"],
    customDays: [],
  },
  {
    id: "4",
    schedule: "everyday",
    timeSpan: "1",
    title: "MIT Technology Review",
    url: "https://www.technologyreview.com/",
    rssLink: "https://www.technologyreview.com/feed/",
    favicon: "https://www.technologyreview.com/static/media/favicon.1cfcdb44759a0f93ddf5feb5405dd4cc.ico",
    tags: ["Technology"],
    customDays: [],
  },
  {
    id: "5",
    title: "Investopedia",
    url: "https://www.investopedia.com",
    rssLink: "https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_articles",
    favicon: "https://www.investopedia.com/favicon.ico",
    tags: ["Finance"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "6",
    title: "BuzzFeed News",
    url: "https://www.buzzfeednews.com",
    rssLink: "https://www.buzzfeednews.com/news.xml",
    favicon: "https://www.buzzfeednews.com/static-assets/img/favicon.40f4055ea10bb11593f4c85d55164232.ico",
    tags: ["General"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "7",
    title: "NYT > Technology",
    url: "https://www.nytimes.com/section/technology",
    rssLink: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    favicon: "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "8",
    title: "Wired",
    url: "https://www.wired.com",
    rssLink: "https://www.wired.com/feed/rss",
    favicon: "https://www.wired.com/verso/static/wired-homepage/assets/favicon.ico",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "9",
    title:
      "Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics",
    url: "https://www.engadget.com/",
    rssLink: "https://www.engadget.com/rss.xml",
    favicon: "https://www.engadget.com/favicon.ico",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "10",
    title: "Computers & Math News -- ScienceDaily",
    url: "https://www.sciencedaily.com/news/computers_math/",
    rssLink: "https://rss.sciencedaily.com/computers_math.xml",
    favicon: "",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "11",
    title: "Gizmodo",
    url: "https://gizmodo.com",
    rssLink: "https://www.gizmodo.com/rss",
    favicon: "https://i.kinja-img.com/image/upload/c_fill,h_80,q_80,w_80/743983ef40322777a7049971bf4faeae.png",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "12",
    title: "Product Hunt",
    url: "https://www.producthunt.com",
    rssLink: "https://www.producthunt.com/feed",
    favicon: "https://ph-static.imgix.net/ph-favicon-coral.ico",
    tags: ["Product"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "13",
    title: "Psychology Research News -- ScienceDaily",
    url: "https://www.sciencedaily.com/news/mind_brain/psychology/",
    rssLink: "https://www.sciencedaily.com/rss/mind_brain/psychology.xml",
    favicon: "",
    tags: ["Psychology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "14",
    title: "PsyBlog",
    url: "https://www.spring.org.uk/",
    rssLink: "https://www.spring.org.uk/feed",
    favicon: "",
    tags: ["Psychology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "15",
    title: "Sustainability",
    url: "https://www.mdpi.com/journal/sustainability",
    rssLink: "https://www.mdpi.com/rss/journal/sustainability",
    favicon: "https://pub.mdpi-res.com/img/journals/sustainability-logo-sq.png?8600e93ff98dbf14",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "16",
    title: "NYT > Business",
    url: "https://www.nytimes.com/section/business",
    rssLink: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    favicon: "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
    tags: ["Economics", "Finance"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "17",
    title: "Astrophysics | Papers Cool",
    url: "https://papers.cool/arxiv/astro-ph",
    rssLink: "https://papers.cool/arxiv/astro-ph/feed",
    favicon: "https://papers.cool/static/favicon.ico",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "18",
    title: "Condensed Matter | Papers Cool",
    url: "https://papers.cool/arxiv/cond-mat",
    rssLink: "https://papers.cool/arxiv/cond-mat/feed",
    favicon: "https://papers.cool/static/favicon.ico",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "19",
    title: "Business Insider",
    url: "https://www.businessinsider.com/",
    rssLink: "https://feeds.businessinsider.com/custom/all",
    favicon: "https://www.businessinsider.com/public/assets/BI/US/favicons/apple-touch-icon-192x192.png?v=2023-11",
    tags: ["Finance"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "20",
    title: "Multimedia | Papers Cool",
    url: "https://papers.cool/arxiv/cs.MM",
    rssLink: "https://papers.cool/arxiv/cs.MM/feed",
    favicon: "https://papers.cool/static/favicon.ico",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "21",
    title: "Machine Learning | Papers Cool",
    url: "https://papers.cool/arxiv/cs.LG",
    rssLink: "https://papers.cool/arxiv/cs.LG/feed",
    favicon: "https://papers.cool/static/favicon.ico",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "22",
    title: "Psyche | on the human condition",
    url: "https://psyche.co",
    rssLink: "https://psyche.co/feed",
    favicon: "https://psyche.co/favicon-32x32.png",
    tags: ["Psychology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "23",
    title: " TechRadar - All the latest technology news ",
    url: "https://www.techradar.com",
    rssLink: "https://www.techradar.com/rss",
    favicon: "https://vanilla.futurecdn.net/techradar/874595/favicon.ico",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "24",
    title: "Frontiers in Psychology | New and Recent Articles",
    url: "https://www.frontiersin.org/journals/psychology",
    rssLink: "https://www.frontiersin.org/journals/psychology/rss",
    favicon: "https://brand.frontiersin.org/m/ed3f9ce840a03d7/favicon_16-tenantFavicon-Frontiers.png",
    tags: ["Psychology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "25",
    title: "Computers and Society | Papers Cool",
    url: "https://papers.cool/arxiv/cs.CY",
    rssLink: "https://papers.cool/arxiv/cs.CY/feed",
    favicon: "https://papers.cool/static/favicon.ico",
    tags: ["Academic"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "26",
    title: "Weekly Wisereads",
    url: "https://wise.readwise.io/feed/",
    rssLink: "https://wise.readwise.io/feed/",
    favicon: "",
    tags: ["General"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "27",
    title: "MIT Technology Review",
    url: "https://www.technologyreview.com",
    rssLink: "https://www.technologyreview.com/feed/",
    favicon: "https://www.technologyreview.com/static/media/favicon.1cfcdb44759a0f93ddf5feb5405dd4cc.ico",
    tags: ["Technology"],
    timeSpan: "1",
    schedule: "everyday",
    customDays: [],
  },
  {
    id: "28",
    rssLink: "https://annieduke.substack.com/feed",
    title: "Thinking in Bets | Annie Duke | Substack",
    tags: [],
    timeSpan: "1",
    url: "https://annieduke.substack.com/",
    schedule: "everyday",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe4a7258c-6a85-4f22-9c4b-286f09a877e8%2Ffavicon.ico",
  },
  {
    id: "29",
    rssLink: "https://bowtiedbull.io/feed",
    schedule: "everyday",
    timeSpan: "1",
    url: "https://bowtiedbull.io/",
    tags: [],
    title: "BowTied Bull | Substack",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F8d524dc9-7d8c-43ee-b53c-742e081fa910%2Ffavicon.ico",
  },
  {
    id: "30",
    schedule: "everyday",
    title: "Exponential View | Azeem Azhar | Substack",
    url: "https://www.exponentialview.co/",
    timeSpan: "1",
    rssLink: "https://www.exponentialview.co/feed",
    tags: [],
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Faa7453ed-eb02-46d7-b523-74d86b1c1e24%2Ffavicon.ico",
  },
  {
    id: "31",
    timeSpan: "1",
    url: "https://thegeneralist.substack.com/",
    tags: [],
    title: "The Generalist | Mario Gabriele | Substack",
    rssLink: "https://thegeneralist.substack.com/feed",
    schedule: "everyday",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe3c721f9-a7fd-4ada-bcef-0e48260a4c8b%2Ffavicon.ico",
  },
  {
    id: "32",
    url: "https://magazine.sebastianraschka.com/",
    schedule: "everyday",
    title: "Ahead of AI | Sebastian Raschka, PhD | Substack",
    timeSpan: "1",
    rssLink: "https://magazine.sebastianraschka.com/feed",
    tags: [],
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fca9744ac-726d-4947-a030-91ea0ab38e23%2Ffavicon.ico",
  },
  {
    id: "33",
    rssLink: "https://tidyfirst.substack.com/feed",
    schedule: "everyday",
    timeSpan: "1",
    tags: [],
    title: "Software Design: Tidy First? | Kent Beck | Substack",
    url: "https://tidyfirst.substack.com/",
    favicon: "https://substackcdn.com/icons/substack/favicon.ico",
  },
  {
    id: "34",
    tags: [],
    timeSpan: "1",
    title: "Cautious Optimism | Alex Wilhelm | Substack",
    rssLink: "https://www.cautiousoptimism.news/feed",
    schedule: "everyday",
    url: "https://www.cautiousoptimism.news/",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F79538bcf-d498-4ade-824e-ac633e039a06%2Ffavicon.ico",
  },
  {
    id: "35",
    rssLink: "https://blog.bytebytego.com/feed",
    timeSpan: "1",
    url: "https://blog.bytebytego.com/",
    schedule: "everyday",
    tags: [],
    title: "ByteByteGo Newsletter | Alex Xu | Substack",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F5507d97a-c736-4de2-852b-fab5b91d0796%2Ffavicon.ico",
  },
  {
    id: "36",
    title: "Liberty’s Highlights | Substack",
    url: "https://www.libertyrpf.com/",
    rssLink: "https://www.libertyrpf.com/feed",
    timeSpan: "1",
    tags: [],
    schedule: "everyday",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F7c962ca0-abd8-4193-819f-3ed883c05b3b%2Ffavicon.ico",
  },
  {
    id: "37",
    tags: [],
    schedule: "everyday",
    url: "https://newsletter.pragmaticengineer.com/",
    title: "The Pragmatic Engineer | Gergely Orosz | Substack",
    rssLink: "https://newsletter.pragmaticengineer.com/feed",
    timeSpan: "1",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F9d53c70a-bdd3-4080-8425-9520ca6acfd4%2Ffavicon.ico",
  },
  {
    id: "38",
    tags: [],
    url: "https://debliu.substack.com/",
    timeSpan: "1",
    title: "Perspectives | Deb Liu | Substack",
    rssLink: "https://debliu.substack.com/feed",
    schedule: "everyday",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Feac32281-2798-428f-a211-03081848adec%2Ffavicon.ico",
  },
  {
    id: "39",
    timeSpan: "1",
    tags: [],
    rssLink: "https://pomp.substack.com/feed",
    url: "https://pomp.substack.com/",
    schedule: "everyday",
    title: "The Pomp Letter | Anthony Pompliano | Substack",
    favicon:
      "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F7ea579f4-b3f2-47d8-901d-4ec4d98079c3%2Ffavicon.ico",
  },
];
